name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: nvmrc=$(cat .nvmrc)
    - uses: actions/checkout@v3
    - id: nvmrc
      uses: browniebroke/read-nvmrc-action@v1
    - uses: actions/setup-node@v3
      with:
        node-version: $nvmrc
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm test -- --watchAll-false